### ISSUE TITLE
Add `jobs` command

### ISSUE THREAD

**Issue by k0va1** [saintprug/saintpruby_bot#11]
I have 2 ways of implementation this feature:
* keep information about jobs in text files
**pros**: easy to implement
**cons**: hard to modify
But if jobs won't be updated this is the best i think.
* store it in a db(hm, redis maybe??)
**pros**: easy to edit, add new jobs; 
**cons**: add new abstraction layer, harder to implement

@IvanShamatov what do you think about all this stuff?

**Comment by IvanShamatov** [comment]
I don't mind about storing everything in text files. There would not be much of them.

, but to have better customer experience, I guess it should return multiple short descriptions and a button to extend the message to see more information about a vacancy.
So the data should be stored in some structure, I'd prefer YAML in that case.
